version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8800:8800"
    environment:
      # you can override these with a .env file or on the command line
      DB_HOST: db.tugapt.nl
      DB_USER: mccp
      DB_PASS: mccp
      DB_NAME: colection
    # if you want to mount code for development, uncomment below:
    # volumes:
    #   - ../:/usr/src/app
    #   - /usr/src/app/node_modules
    # command: npm run start
